# local 환경
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/studyProject
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaROJfrg"
  expiration: 3600000 # 토큰 만료 시간 (1시간 = 3600000ms)